- menu_name: "Spletne storitve"

- name: "Kontakt"
  url: "/contact/"
  title: "Kontakt"

- name: "RSS"
  url: "/feed.xml"
  title: "Naroči se na RSS vir"

- name: "Atom"
  url: "/atom.xml"
  title: "Naroči se na Atom vir"

- name: "sitemap.xml"
  url: "/sitemap.xml"
  title: "Načrt strani za Googleova spletna orodja"
